apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd
  namespace: notepad
spec:
  claim:
    name: hackmd
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1
---
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd-postgresql
  namespace: notepad
spec:
  claim:
    name: data-hackmd-postgresql-0
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1

