version: 2.1
orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@10.1

executors:
  vm:
    machine:
      enabled: true

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        echo 'export PUSH_ALL_VERSION_TAGS=true' >> ${BASH_ENV}
        echo 'export GOPROXY=https://proxy.golang.org' >> ${BASH_ENV}
        echo 'export GO111MODULE=on' >> ${BASH_ENV}


  go_test: &go_test
    run:
      name: Test Golang
      command: |
        go get -u golang.org/x/lint/golint
        go list ./... | grep -v types | xargs golint -set_exit_status
        go list ./... | grep -v types | xargs go vet

        go get -u gotest.tools/gotestsum
        mkdir -p /tmp/test-results/go
        gotestsum --junitfile /tmp/test-results/go/results.xml -- ./pkg/... -cover -covermode atomic -coverpkg=./... -coverprofile=coverage.txt
        bash <(curl -s https://codecov.io/bash)

  docker_build_and_push: &docker_build_and_push
    run:
      name: Docker login, build, and push
      command: |
        docker-pull -f .circleci/build.config
        docker-build -f .circleci/build.config
        if [[ -z $CIRCLE_PR_NUMBER ]]; then
          docker login quay.io -u="${fairwinds_quay_user}" -p="${fairwinds_quay_token}"
          docker-push -f .circleci/build.config
        else
          echo "Skipping docker push for forked PR"
        fi

jobs:
  build:
    docker:
      - image: quay.io/reactiveops/ci-images:v8.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *docker_build_and_push

  test:
    working_directory: /go/src/github.com/fairwindsops/photon/
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - *set_environment_variables
      - *go_test

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          context: org-global
          filters:
            tags:
              only: /^testing-.*/
  e2e_test:
    jobs:
      - rok8s-scripts/kubernetes_e2e_tests:
          name: End-To-End Test on Kubernetes 1.16
          pre_script: e2e/pre.sh
          script: e2e/test.sh
          kind_node_image: >-
            kindest/node:v1.15.6@sha256:18c4ab6b61c991c249d29df778e651f443ac4bcd4e6bdd37e0c83c0d33eaae78
      - rok8s-scripts/kubernetes_e2e_tests:
          name: End-To-End Test on Kubernetes 1.17
          pre_script: e2e/pre.sh
          script: e2e/test.sh
          kind_node_image: >-
            kindest/node:v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a

  release:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^testing-.*/
