version: 2.1

executors:
  vm:
    machine:
      enabled: true

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        echo 'export PUSH_ALL_VERSION_TAGS=true' >> ${BASH_ENV}
        echo 'export GOPROXY=https://proxy.golang.org' >> ${BASH_ENV}
        echo 'export GO111MODULE=on' >> ${BASH_ENV}


  update_coverage: &update_coverage
    run:
      name: Update Coverage
      command: |
        if [[ -z $CIRCLE_PR_NUMBER ]]; then
          bash <(curl -s https://codecov.io/bash)
        else
          echo "Skipping coverage for forked PR"
        fi

  docker_build_and_push: &docker_build_and_push
    run:
      name: Docker login, build, and push
      command: |
        docker-pull -f .circleci/build.config
        docker-build -f .circleci/build.config
        if [[ -z $CIRCLE_PR_NUMBER ]]; then
          docker login quay.io -u="${fairwinds_quay_user}" -p="${fairwinds_quay_token}"
          docker-push -f .circleci/build.config
        else
          echo "Skipping docker push for forked PR"
        fi

jobs:
  build:
    docker:
      - image: quay.io/reactiveops/ci-images:v8.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *docker_build_and_push

  test:
    working_directory: /go/src/github.com/fairwindsops//
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - *set_environment_variables
      - run: go get -u golang.org/x/lint/golint
      - run: go list ./... | grep -v types | xargs golint -set_exit_status
      - run: go list ./... | grep -v types | xargs go vet
      - run: go test ./pkg/... -coverprofile=coverage.txt -covermode=count
      - *update_coverage

  release_images:
    working_directory: /go/src/github.com/fairwindsops/photon/
    docker:
      - image: quay.io/reactiveops/ci-images:v8.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *docker_build_and_push

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          context: org-global
          # Allow using testing tags for testing circle test + build steps
          filters:
            tags:
              only: /^testing-.*/
  release:
    jobs:
      - release_images:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            # Testing tags are reserved for testing circle test + build steps
            tags:
              ignore: /^testing-.*/
