apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd
  namespace: notepad
spec:
  pvc:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1
---
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd-postgresql
  namespace: notepad
spec:
  pvc:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1

