apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: ebs-photon-testing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
