apiVersion: photon.fairwinds.com/v1
kind: SnapshotGroup
metadata:
  name: hackmd-postgresql
  namespace: notepad
spec:
  claim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
  schedule:
    - every: minute
      keep: 3
    - every: "2 minutes"
      keep: 6
